select distinct e.ACCESSION as STUDY, s.ACCESSION as BIOENTITY, p.NAME as PROPERTY_TYPE, pv.NAME as PROPERTY_VALUE, ot.ACCESSION as SEMANTIC_TAG
from A2_EXPERIMENT e
inner join A2_SAMPLE s on e.EXPERIMENTID = s.EXPERIMENTID
inner join A2_SAMPLEPV spv on s.SAMPLEID = spv.SAMPLEID
inner join A2_PROPERTYVALUE pv on spv.PROPERTYVALUEID = pv.PROPERTYVALUEID
inner join A2_PROPERTY p on pv.PROPERTYID = p.PROPERTYID
left join A2_SAMPLEPVONTOLOGY spvo on spv.SAMPLEPVID = spvo.SAMPLEPVID
inner join A2_ONTOLOGYTERM ot on spvo.ONTOLOGYTERMID = ot.ONTOLOGYTERMID